### ISSUE TITLE
ScriptManager no longer works with latest Torch/Space Engineers 

### ISSUE THREAD

**Issue by JamieKG** [theCalcaholic/TorchScriptManager#3]
Hi im not sure if you are actively working on this plugin anymore but since the latest update of SE and Torch this plugin no longer works due to keens changes I beleave
![image](https://user-images.githubusercontent.com/3878484/59150229-076ddf00-8a18-11e9-9157-8ce97147431c.png)

Thanks JamieKG

Error message when lunching torch with only this plugin installed 
`16:59:05.5965 [INFO]   Torch: Initializing server
16:59:05.8531 [INFO]   Torch: RELEASE
16:59:05.8531 [INFO]   Torch: Torch Version: v1.3.1.47-master
16:59:05.8531 [INFO]   Torch: Game Version: 1.191.23
16:59:05.8531 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.1.47, Culture=neutral, PublicKeyToken=null
16:59:05.8531 [INFO]   Torch: Executing directory: C:\GameServers\SpaceE Test\
16:59:05.8531 [INFO]   Torch.Managers.PluginManager: Checking for plugin updates...
16:59:05.9614 [INFO]   Torch.Managers.PluginManager: Updated 0 plugins.
16:59:05.9614 [INFO]   Torch.Managers.PluginManager: Loading plugins...
16:59:06.1740 [ERROR]  Initializer: Error initializing server.
16:59:06.1750 [FATAL]  Initializer: System.TypeLoadException: Could not load type 'ProtoBuf.ProtoContractAttribute' from assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at System.Reflection.CustomAttribute.IsDefined(RuntimeType type, RuntimeType caType, Boolean inherit)
   at Torch.Utils.ReflectedManager.Process(Assembly asm) in C:\jenkins\workspace\Torch_Torch_master\Torch\Utils\Reflected\ReflectedManager.cs:line 81
   at Torch.TorchBase.RegisterAuxAssembly(Assembly asm) in C:\jenkins\workspace\Torch_Torch_master\Torch\TorchBase.cs:line 488
   at Torch.Managers.PluginManager.RegisterAllAssemblies(IReadOnlyCollection`1 assemblies) in C:\jenkins\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 340
   at Torch.Managers.PluginManager.LoadPluginFromZip(String path) in C:\jenkins\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 315
   at Torch.Managers.PluginManager.LoadPlugins() in C:\jenkins\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 122
   at Torch.TorchBase.Init() in C:\jenkins\workspace\Torch_Torch_master\Torch\TorchBase.cs:line 338
   at Torch.Server.TorchServer.Init() in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 100
   at System.Threading.Tasks.Task.Execute()
System.TypeLoadException: Could not load type 'ProtoBuf.ProtoContractAttribute' from assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at System.Reflection.CustomAttribute.IsDefined(RuntimeType type, RuntimeType caType, Boolean inherit)
   at Torch.Utils.ReflectedManager.Process(Assembly asm) in C:\jenkins\workspace\Torch_Torch_master\Torch\Utils\Reflected\ReflectedManager.cs:line 81
   at Torch.TorchBase.RegisterAuxAssembly(Assembly asm) in C:\jenkins\workspace\Torch_Torch_master\Torch\TorchBase.cs:line 488
   at Torch.Managers.PluginManager.RegisterAllAssemblies(IReadOnlyCollection`1 assemblies) in C:\jenkins\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 340
   at Torch.Managers.PluginManager.LoadPluginFromZip(String path) in C:\jenkins\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 315
   at Torch.Managers.PluginManager.LoadPlugins() in C:\jenkins\workspace\Torch_Torch_master\Torch\Plugins\PluginManager.cs:line 122
   at Torch.TorchBase.Init() in C:\jenkins\workspace\Torch_Torch_master\Torch\TorchBase.cs:line 338
   at Torch.Server.TorchServer.Init() in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 100
   at System.Threading.Tasks.Task.Execute()
`

**Comment by Sipowicz** [comment]
Having the same error.

**Comment by Bishbash777** [comment]
Hello - i have successfully fixed a version of this plugin - it was broken due to STEAM changing their API so now the URL of where the script file is stored for download is not public anymore so now scripts have to be manually added and pasted into the GUI 


Find me on the torch discord (Bishbash777) and PM me for a download

**Comment by theCalcaholic** [comment]
Thanks for reporting these bugs. I'm currently not actively working on this, because I don't have a development environment for it (no running version of Windows).
I won't say that I will never continue working on this project, I just can't guarantee that this happens at any point.

In the meantime, if anyone wants to maintain this repository, feel free to contact me, send me PRs, etc.
However, this is FOSS (free open source software). Selling versions of the plugin while disclosing (or publishing under a non-open-source license) their source code is **illegal**. If you do receive any offers of this kind, please inform me so I can take actions.

**Comment by Bishbash777** [comment]
@theCalcaholic i will look to make a PR but the plugin now has lesser functionality (missing the ability to add script via ID) This is because steam have changed their API which means the plugin now gets a null response when looking for the file url (steam does not allow this information to be public anymore). As well as that, protobuf and multiple SE dependencies needed to be updated to stop fatal crash on server startup
